name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Zip
        # run: zip -r main.zip cfg materials

      - uses: actions/upload-artifact@v4.6.2
        with:
          path: cfg materials
          compression-level: 9
          name: config
